### ISSUE TITLE
How can I get the matched range?

### ISSUE THREAD

**Issue by singno** [sharplet/Regex#26]

**Comment by sharplet** [comment]
Hi @singno!

This is something I've considered, however I'd like to talk about concrete use cases before adding it. Would you mind elaborating on your use case?

**Comment by sharplet** [comment]
Just FYI, I ended up adding a range property to MatchResult as part of #31. If you think there's a compelling use case for it beyond find and replace, I'll definitely consider going ahead and making it public!

**Comment by singno** [comment]
It sounds great! And sometimes I want to replace part of NSAttributedString, would you also support this use cases?

**Comment by sharplet** [comment]
@singno I've just released version [0.3.1](../releases/0.3.1) which includes range replacement methods.

At this stage I think `NSAttributedString` integration is out of scope for this library. Because `NSRegularExpression` itself doesn't have direct integration with `NSAttributedString`.

However, it may be worth exposing a `utf16range` property on `MatchResult`, which you could then pass to `NSMutableAttributedString.replaceCharactersInRange(_:withString:)` et al. Would that work for your use case?

**Comment by sharplet** [comment]
`NSAttributedString` support has come up in another issue as well, so I've opened #38 to track that into the future. I'm going to close this for now.
