### ISSUE TITLE
MacthResult does not provide Range & NSTextCheckingResult (if install as Framework)

### ISSUE THREAD

**Issue by av0c0der** [sharplet/Regex#37]
Thank you for this easy and useful tool! 

I was use it included in project as files. But now I was installed it through `Carthage` and `MatchResult` lost `Range` & `NSTextCheckingResult` properties.

**Comment by sharplet** [comment]
You're welcome!

At the moment, `range` and `matchResult` are internal API, as I consider them implementation details. In general I'd prefer to add new public API rather than exposing `Foundation` types, if possible.

Would you mind sharing an example of how you're using those properties?

**Comment by av0c0der** [comment]
I've been used `replaceRange(subRange: Range<Index>, with newElements: String)`; `removeRange(subRange: Range<Index>)` methods and `NSTextCheckingResult`'s `range` property for creating `NSAttributedString`.

**Comment by sharplet** [comment]
Instead of `replaceRange()`, you can use Regex's `String.replaceFirstMatching(_:with:)` and `String.replaceAllMatching(_:with:)` methods. Instead of `removeRange` you can do the same thing but with the empty string as the replacement.

`NSAttributedString` support has come up before, so I'd like to track that as a separate issue: #38. However, I'd appreciate it if you could share a code snippet showing an example of how you were using Regex with `NSAttributedString` before you switched to Carthage?

I'm going to close this issue for now, but let me know if you have any further questions.
